<a href="https://colab.research.google.com/github/leonardoleandrodev/covidMachineLearningPrediction/blob/main/DEEP_LEARNING_KERAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from numpy import loadtxt
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from pandas import read_csv as rc,factorize as fc,to_numeric as tnum,set_option as op

In [ ]:
# dados do site https://opendatasus.saude.gov.br/dataset/bd-srag-2021
urlfile = 'https://opendatasus.saude.gov.br/dataset/9f76e80f-a2f1-4662-9e37-71084eae23e3/resource/42bd5e0e-d61a-4359-942e-ebc83391a137/download/influd21-18-06-2021.csv'
#https://opendatasus.saude.gov.br/dataset/9f76e80f-a2f1-4662-9e37-71084eae23e3/resource/b3321e55-24e9-49ab-8651-29cf5c8f3179/download/dicionario_de_dados_srag_hospitalizado_23.03.2021.pdf
dataset = rc(urlfile, delimiter=';',encoding='ISO-8859-1')


/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (15,18,60,62,63,64,92,94,106,108,115,117,118,119,123,144,160) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [ ]:
op('display.max_columns', None)
dataset.head(10)


DT_NOTIFIC  SEM_NOT  DT_SIN_PRI  SEM_PRI SG_UF_NOT          ID_REGIONA  \
0  06/01/2021        1  05/01/2021        1        SP  GVE XII ARARAQUARA   
1  09/01/2021        1  08/01/2021        1        MG          UBERLANDIA   
2  10/01/2021        2  05/01/2021        1        SP       GVE XXX JALES   
3  10/01/2021        2  08/01/2021        1        RS             002 CRS   
4  14/01/2021        2  03/01/2021        1        SC            CRICIUMA   
5  09/01/2021        1  06/01/2021        1        GO       ENTORNO NORTE   
6  09/01/2021        1  03/01/2021        1        SP   GVE XVII CAMPINAS   
7  15/01/2021        2  10/01/2021        2        SE    REGIONAL ARACAJU   
8  15/01/2021        2  10/01/2021        2        GO             CENTRAL   
9  14/01/2021        2  04/01/2021        1        MG         DIVINOPOLIS   

   CO_REGIONA      ID_MUNICIP  CO_MUN_NOT  \
0      1337.0        ITAPOLIS      352270   
1      1462.0      UBERLANDIA      317020   
2      1574.0           JALES      352480   
3      1607.0    PORTO ALEGRE      431490   
4      1558.0        CRICIUMA      420460   
5      1784.0         FORMOSA      520800   
6      1342.0        CAMPINAS      350950   
7      2056.0         ARACAJU      280030   
8      1779.0         GOIANIA      520870   
9      1472.0  LAGOA DA PRATA      313720   

                                          ID_UNIDADE  CO_UNI_NOT CS_SEXO  \
0                SANTA CASA DE MISERICORDIA ITAPOLIS     2079836       M   
1                                      UAI SAO JORGE     5617286       M   
2                SANTA CASA DE MISERICORDIA DE JALES     2079895       M   
3                     HOSPITAL GERAL DE PORTO ALEGRE     7989954       F   
4                           HOSPITAL UNIMED CRICIUMA     5712068       M   
5   HOSPITAL REGIONAL DE FORMOSA DR CESAR SAAD FAYAD     2534967       F   
6              HOSPITAL E MATERNIDADE MADRE THEODORA     2078678       F   
7                                  HOSPITAL SAO JOSE        2275       M   
8  HOSPITAL DE ENFRENTAMENTO AO CORONAVIRUS DE GO...       86126       F   
9                                HOSPITAL SAO CARLOS     2132877       F   

      DT_NASC  NU_IDADE_N  TP_IDADE COD_IDADE  CS_GESTANT  CS_RACA CS_ETINIA  \
0  26/03/1953          67         3      3067           6        2       NaN   
1  07/05/2002          18         3      3018           6        2       NaN   
2  15/10/1963          57         3      3057           6        1       NaN   
3  03/07/1937          83         3      3083           5        1       NaN   
4  08/05/1958          62         3      3062           6        1       NaN   
5  31/08/1957          63         3      3063           5        1       NaN   
6  29/04/1956          64         3      3064           5        9       NaN   
7  20/01/1975          45         3      3045           6        4       NaN   
8  05/08/1948          72         3      3072           9        4       NaN   
9  12/12/1964          56         3      3056           6        1       NaN   

   CS_ESCOL_N ID_PAIS  CO_PAIS SG_UF          ID_RG_RESI  CO_RG_RESI  \
0         NaN  BRASIL        1    SP  GVE XII ARARAQUARA      1337.0   
1         9.0  BRASIL        1    MG          UBERLANDIA      1462.0   
2         9.0  BRASIL        1    SP       GVE XXX JALES      1574.0   
3         9.0  BRASIL        1    RS             002 CRS      1607.0   
4         3.0  BRASIL        1    SC            CRICIUMA      1558.0   
5         2.0  BRASIL        1    GO       ENTORNO NORTE      1784.0   
6         9.0  BRASIL        1    SP   GVE XVII CAMPINAS      1342.0   
7         NaN  BRASIL        1    SE    REGIONAL SOCORRO      2061.0   
8         1.0  BRASIL        1    GO             CENTRAL      1779.0   
9         1.0  BRASIL        1    MG         DIVINOPOLIS      1472.0   

       ID_MN_RESI  CO_MUN_RES  CS_ZONA  SURTO_SG  NOSOCOMIAL  AVE_SUINO  \
0        ITAPOLIS    352270.0      1.0       NaN         NaN        NaN  

In [ ]:
amostra = dataset[
                  ['CS_SEXO','NU_IDADE_N','FEBRE','TOSSE',
                   'GARGANTA','DIARREIA','VOMITO','OUTRO_SIN',
                   'CARDIOPATI','HEMATOLOGI','HEPATICA','ASMA',
                   'DIABETES','PNEUMOPATI','RENAL','OBESIDADE',
                   'ANTIVIRAL','UTI','DOR_ABD','FADIGA'
                   ,'PERD_OLFT','PERD_PALA','EVOLUCAO','CLASSI_FIN']]#[1:10000]
amostra = amostra.dropna()
#amostra['IdadeNaDataNotificacao'] = [int(idade.split(' ')[0]) for idade in amostra['IdadeNaDataNotificacao']]
#amostra['IdadeNaDataNotificacao'] = [int(idade.split(' ')[0]) for idade in amostra['IdadeNaDataNotificacao']]
#amostra = amostra.drop(amostra[amostra.ResultadoTesteRapido == 'Não Informado'].index)
#amostra = amostra.drop(amostra[amostra.ResultadoTesteRapido == 'Inconclusivo'].index)
#amostra = amostra.drop(amostra[amostra.ComorbidadePulmao == '-'].index)
#amostra = amostra.drop(amostra[amostra.RacaCor == 'Ignorado'].index)
amostra = amostra.drop(amostra[amostra.NU_IDADE_N < 20 ].index)
amostra = amostra.drop(amostra[amostra.EVOLUCAO > 2 ].index)
amostra = amostra.drop(amostra[amostra.FEBRE > 2 ].index)
amostra = amostra.drop(amostra[amostra.TOSSE > 2 ].index)
amostra = amostra.drop(amostra[amostra.GARGANTA > 2 ].index)
amostra = amostra.drop(amostra[amostra.FADIGA > 2 ].index)
amostra = amostra.drop(amostra[amostra.PERD_OLFT > 2 ].index)
amostra = amostra.drop(amostra[amostra.PERD_PALA > 2 ].index)
amostra = amostra.drop(amostra[amostra.UTI > 2 ].index)
#amostra = amostra.drop(amostra[amostra.Classificacao == 'Suspeito' ].index)
#amostra = amostra.drop(amostra[amostra.Evolucao == 'Ignorado'].index)
#amostra = amostra.drop(amostra[amostra.Evolucao == '-'].index)
#amostra = amostra.drop(amostra[amostra.Evolucao == 'Óbito por outras causas'].index)

amostra.head()


CS_SEXO  NU_IDADE_N  FEBRE  TOSSE  GARGANTA  DIARREIA  VOMITO  OUTRO_SIN  \
0       M          67    2.0    1.0       2.0       9.0     1.0        2.0   
3       F          83    2.0    2.0       2.0       2.0     2.0        1.0   
4       M          62    2.0    1.0       2.0       2.0     2.0        2.0   
5       F          63    2.0    1.0       2.0       2.0     2.0        2.0   
6       F          64    1.0    1.0       2.0       2.0     2.0        2.0   

   CARDIOPATI  HEMATOLOGI  HEPATICA  ASMA  DIABETES  PNEUMOPATI  RENAL  \
0         1.0         2.0       2.0   2.0       2.0         2.0    2.0   
3         1.0         2.0       2.0   2.0       2.0         2.0    2.0   
4         2.0         2.0       2.0   1.0       2.0         2.0    2.0   
5         2.0         2.0       2.0   2.0       1.0         2.0    2.0   
6         2.0         2.0       2.0   2.0       1.0         2.0    2.0   

   OBESIDADE  ANTIVIRAL  UTI  DOR_ABD  FADIGA  PERD_OLFT  PERD_PALA  EVOLUCAO  \
0        2.0        2.0  2.0      2.0     2.0        2.0        2.0       1.0   
3        2.0        9.0  2.0      2.0     2.0        2.0        2.0       1.0   
4        2.0        2.0  2.0      2.0     2.0        2.0        2.0       1.0   
5        2.0        2.0  1.0      2.0     2.0        2.0        2.0       2.0   
6        1.0        1.0  2.0      2.0     2.0        2.0        2.0       1.0   

   CLASSI_FIN  
0         4.0  
3         4.0  
4         5.0  
5         5.0  
6         5.0

In [ ]:
colunas = ['FADIGA','PERD_OLFT','PERD_PALA','CLASSI_FIN','UTI']
classe = colunas[-1]
amostrax = amostra[colunas]

amostrax['CLASSI_FIN'] = amostrax['CLASSI_FIN']#.apply(lambda x: 1 if x == 5.0 else 0)
#amostrax['CS_SEXO'] = amostrax['CS_SEXO'].replace('F',0).replace('M',1)
#amostrax = amostrax[[c for c in colunas]]
#amostrax['NU_IDADE_N'] = [round(idd/10)*10 for idd  in amostrax['NU_IDADE_N']]
dados = amostrax.replace(1.0,1).replace(2.0,0)

#dados[colunas] = dados[colunas].astype(int)
del dados[classe]
resnegposi = dados[colunas[:-1]].sum(axis=1).apply(lambda x: 1 if x > 6.0 else 0)
#amostrax[[classe]].replace(1.0,1).replace(2.0,0)#.replace('Descartados',0).replace('Confirmados',1).replace('Negativo',0).replace('Positivo',1)
dados[20:].head(10) 
resnegposi.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


0    0
3    0
4    0
5    0
6    0
dtype: int64

In [ ]:

dadosX = dados.apply(lambda col: fc(col)[0] if col.name == 'CS_SEXO' else col)
dadosX = dadosX.apply(tnum)
resnegposiY = resnegposi#.apply(lambda col: fc(col)[0])

#resnegposiY.info()

In [ ]:
from sklearn.model_selection import train_test_split
val_treino,val_teste,val_res_treino,val_res_teste = train_test_split(dadosX,resnegposiY,test_size=0.001,train_size=0.01)
(len(val_treino),len(val_teste))

(2032, 204)

In [ ]:
# definir o modelo com keras
# inicializar o modelo sequencial
model = Sequential()
# inicializar a primeira camada, com 12 neurônios, 8 entradas utilizando a função ReLU
model.add(Dense(7, input_dim=(len(val_treino.columns)), activation='relu'))
# inicializar a segunda camada com 8 neurônios e a função ReLU
#model.add(Dense(20, activation='relu'))
#model.add(Dense(20, activation='relu'))
#model.add(Dense(len(val_treino.columns), activation='relu'))
# inicializar a última camada (camada de saída) com um neurônio e a função Sigmoid
model.add(Dense(1, activation='sigmoid'))

In [ ]:
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])


In [ ]:
# treinar o modelo keras

model.fit(val_treino, val_res_treino, epochs=150, batch_size=10,use_multiprocessing=False,verbose=1)


Epoch 1/150
204/204 [==============================] - 1s 1ms/step - loss: 0.5055 - accuracy: 0.9071
Epoch 2/150
204/204 [==============================] - 0s 1ms/step - loss: 0.3394 - accuracy: 0.9079
Epoch 3/150
204/204 [==============================] - 0s 1ms/step - loss: 0.2959 - accuracy: 0.9068
Epoch 4/150
204/204 [==============================] - 0s 1ms/step - loss: 0.2855 - accuracy: 0.9032
Epoch 5/150
204/204 [==============================] - 0s 1ms/step - loss: 0.2654 - accuracy: 0.9053
Epoch 6/150
204/204 [==============================] - 0s 1ms/step - loss: 0.2631 - accuracy: 0.8974
Epoch 7/150
204/204 [==============================] - 0s 1ms/step - loss: 0.2381 - accuracy: 0.9043
Epoch 8/150
204/204 [==============================] - 0s 1ms/step - loss: 0.2284 - accuracy: 0.8942
Epoch 9/150
204/204 [==============================] - 0s 1ms/step - loss: 0.1782 - accuracy: 0.9111
Epoch 10/150
204/204 [==============================] - 0s 1ms/step - loss: 0.1616 - accura

In [ ]:
predictions = model.predict(val_teste)
sum = 0.0
for k in predictions:
  sum += k

md = (sum /len(predictions))-0.05
print(md)
predictionsi = [0 if p < 0.5 else 1 for p in predictions]
from sklearn.metrics import confusion_matrix,accuracy_score
accuracy = accuracy_score(val_res_teste, predictionsi)
mt = confusion_matrix(val_res_teste, predictionsi)
print(mt,f'acuracia de {accuracy} %')
for i,x in enumerate(predictionsi):
  if x != val_res_teste.values[i]:
    print(val_teste.values[i][0:],predictions[i],x,val_res_teste.values[i])
  #print(f'data={val_teste.values[i]} {predictions[i]}% {val_res_teste.values[i]} {x}')


[0.03549984]
[[186   2]
 [  0  16]] acuracia de 0.9901960784313726 %
[0. 1. 1. 4.] [0.96899164] 1 0
[1. 0. 1. 4.] [0.96899164] 1 0
